require 'fileutils'

SPEAKERS = Dir.glob('*').select &File.method(:directory?)

namespace :make do
  desc "Convert each speaker's EAF files to CSV"
  task :csv do
    SPEAKERS.each do |speaker|
      # Create speaker's CSV subdirectory
      csv_dir = File.join(speaker, 'eaf.csv')
      FileUtils.mkdir_p csv_dir

      # Convert each speaker's EAF files to CSV
      Dir.glob File.join(speaker, 'eaf', '*.eaf') do |eaf|
        csv = File.join csv_dir, "#{File.basename(eaf)}.csv"
        system %{python2 eaf2csv.py #{eaf} #{csv}}
      end
    end
  end
end

namespace :destroy do
  desc "Destroy converted CSV files"
  task :csv do
    SPEAKERS.each do |speaker|
      FileUtils.rm_r File.join(speaker, 'eaf.csv')
    end
  end

  desc "Destroy .pfsx files"
  task :pfsx do
    FileUtils.rm Dir.glob('**/*.pfsx')
  end
end