require 'fileutils'

SPEAKERS = %w[Adam Beve Brian Dani Ella Esmo Paul Sophie]

namespace :make do
  desc "Convert each speaker's EAF files to CSV"
  task :csv do
    SPEAKERS.each do |speaker|
      # Create speaker's CSV subdirectory
      csv_dir = File.join(speaker, 'csv')
      FileUtils.mkdir_p csv_dir

      # Convert each speaker's EAF files to CSV
      Dir.glob File.join(speaker, 'eaf', '*.eaf') do |eaf|
        file_name = File.basename(eaf, '.eaf')
        csv = File.join csv_dir, "#{file_name}.csv"
        system %{python2 eaf2csv.py #{eaf} #{csv}}
      end
    end
  end
end

namespace :destroy do
  desc "Destroy converted CSV files"
  task :csv do
    SPEAKERS.each do |speaker|
      Dir.glob File.join(speaker, 'csv', '*.csv') do |csv|
        FileUtils.rm csv
      end
    end
  end
end